// Comprehensive Mock Data Catalog for OpenPath Platform
// Derived from official database seeding catalog with high-fidelity opportunities, skills, and demo users

export const INITIAL_SKILLS = [
  { _id: 'sk_1', name: 'React', category: 'Frontend', description: 'Component-based UI library for web development' },
  { _id: 'sk_2', name: 'JavaScript', category: 'Programming', description: 'Core web scripting language (ES6+)' },
  { _id: 'sk_3', name: 'TypeScript', category: 'Programming', description: 'Typed superset of JavaScript' },
  { _id: 'sk_4', name: 'Node.js', category: 'Backend', description: 'Server-side JavaScript runtime environment' },
  { _id: 'sk_5', name: 'Express.js', category: 'Backend', description: 'Minimalist web application framework for Node.js' },
  { _id: 'sk_6', name: 'MongoDB', category: 'Database', description: 'Document-oriented NoSQL database system' },
  { _id: 'sk_7', name: 'SQL', category: 'Database', description: 'Relational database query language' },
  { _id: 'sk_8', name: 'Python', category: 'Programming', description: 'High-level language widely used in AI, ML & backend' },
  { _id: 'sk_9', name: 'Machine Learning', category: 'Data & AI', description: 'Statistical algorithms and predictive modeling' },
  { _id: 'sk_10', name: 'Figma', category: 'Design', description: 'Collaborative web-based UI/UX design tool' },
  { _id: 'sk_11', name: 'UI/UX Design', category: 'Design', description: 'User research, wireframing, and visual interfaces' },
  { _id: 'sk_12', name: 'Tailwind CSS', category: 'Frontend', description: 'Utility-first CSS framework for rapid styling' },
  { _id: 'sk_13', name: 'Git', category: 'DevOps & Tools', description: 'Distributed version control and collaboration' },
  { _id: 'sk_14', name: 'REST APIs', category: 'Backend', description: 'Standard HTTP communication architecture' },
  { _id: 'sk_15', name: 'Docker', category: 'DevOps & Tools', description: 'Containerization and environment reproducibility' },
  { _id: 'sk_16', name: 'AWS', category: 'Cloud', description: 'Amazon Web Services cloud computing infrastructure' },
  { _id: 'sk_17', name: 'Data Structures', category: 'Computer Science', description: 'Fundamental algorithms and problem solving' },
  { _id: 'sk_18', name: 'HTML & CSS', category: 'Frontend', description: 'Core building blocks of the responsive web' },
  { _id: 'sk_19', name: 'GraphQL', category: 'Backend', description: 'Query language for APIs and runtime executor' },
  { _id: 'sk_20', name: 'Next.js', category: 'Frontend', description: 'Full-stack React framework with SSR and SSG' },
];

export const DEMO_STUDENT = {
  _id: 'usr_student_alex',
  name: 'Alex Rivera',
  email: 'alex.rivera@university.edu',
  role: 'student',
  bio: 'Pre-final year Computer Science undergraduate passionate about building accessible user interfaces and modern web applications with React, Three.js, and TypeScript.',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=250',
  resumeUrl: 'https://openpath.internal/resumes/alex_rivera_resume.pdf',
  education: {
    degree: 'Bachelor of Technology (B.Tech)',
    institution: 'Indian Institute of Information Technology',
    fieldOfStudy: 'Computer Science & Engineering',
    startYear: '2022',
    endYear: '2026',
    grade: '8.8 CGPA',
  },
  skills: [
    { _id: 'sk_1', name: 'React', category: 'Frontend' },
    { _id: 'sk_2', name: 'JavaScript', category: 'Programming' },
    { _id: 'sk_18', name: 'HTML & CSS', category: 'Frontend' },
    { _id: 'sk_12', name: 'Tailwind CSS', category: 'Frontend' },
    { _id: 'sk_13', name: 'Git', category: 'DevOps & Tools' },
    { _id: 'sk_14', name: 'REST APIs', category: 'Backend' },
  ],
  interests: ['Frontend Engineering', 'UI/UX Design', 'Full-stack Web Development', 'Open Source'],
  experience: {
    role: 'Frontend Contributor',
    organization: 'Campus Open Source Guild',
    duration: '6 Months',
    description: 'Built interactive dashboards and automated form components using React and REST APIs.',
  },
  location: {
    city: 'Bengaluru',
    state: 'Karnataka',
    country: 'India',
    remotePreference: 'Remote',
  },
  profileCompleted: true,
};

export const DEMO_EMPLOYER = {
  _id: 'usr_employer_sarah',
  name: 'Sarah Jenkins',
  email: 'recruiter@techcorp.io',
  role: 'employer',
  bio: 'Head of University Relations & Early Career Talent at TechCorp Labs. Passionate about empowering the next generation of engineers.',
  avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=250',
  companyDetails: {
    companyName: 'TechCorp Labs',
    logo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&q=80&w=200',
    industry: 'Cloud Software & Developer Tools',
    description: 'TechCorp builds next-generation productivity infrastructure for teams worldwide.',
    website: 'https://techcorp.io',
    hiringTypes: ['Internship', 'Apprenticeship', 'Entry-level Job'],
  },
  location: {
    city: 'Bengaluru',
    state: 'Karnataka',
    country: 'India',
  },
  profileCompleted: true,
};

export const INITIAL_OPPORTUNITIES = [
  {
    _id: 'opp_1',
    title: 'Frontend Engineering Intern',
    organization: 'TechCorp Labs',
    organizationLogo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&q=80&w=200',
    type: 'Internship',
    matchScore: 94,
    requiredSkills: [
      { _id: 'sk_1', name: 'React', category: 'Frontend' },
      { _id: 'sk_2', name: 'JavaScript', category: 'Programming' },
      { _id: 'sk_12', name: 'Tailwind CSS', category: 'Frontend' },
      { _id: 'sk_14', name: 'REST APIs', category: 'Backend' },
      { _id: 'sk_13', name: 'Git', category: 'DevOps & Tools' },
    ],
    qualification: {
      degree: 'Bachelor of Technology (B.Tech)',
      field: 'Computer Science or IT',
      minCgpa: 7.0,
    },
    experienceRequired: {
      minYears: 0,
      level: 'Fresher / Student',
    },
    location: {
      type: 'Remote',
      city: 'Bengaluru',
      state: 'Karnataka',
      country: 'India',
    },
    interests: ['Frontend Engineering', 'UI/UX Design', 'Full-stack Web Development'],
    salary: {
      amount: '₹35,000',
      period: 'month',
      currency: '₹',
      isUnpaid: false,
    },
    deadline: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'Active',
    applicantCount: 24,
    description:
      'Join our frontend core team to build accessible, high-performance web interfaces used by over 500,000 developers. You will collaborate with senior engineers and product designers on real production features.',
    responsibilities: [
      'Develop reusable React UI components following our design system',
      'Integrate REST endpoints and manage local UI states',
      'Write clean semantic HTML and responsive CSS layouts',
      'Participate in code reviews and pair programming sessions',
    ],
    requirements: [
      'Solid understanding of React fundamentals, hooks, and JavaScript ES6+',
      'Familiarity with Git branching and pull requests',
      'Eagerness to learn in a supportive collaborative engineering culture',
    ],
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    _id: 'opp_2',
    title: 'Junior Full-Stack Developer',
    organization: 'TechCorp Labs',
    organizationLogo: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=200',
    type: 'Entry-level Job',
    matchScore: 82,
    requiredSkills: [
      { _id: 'sk_1', name: 'React', category: 'Frontend' },
      { _id: 'sk_4', name: 'Node.js', category: 'Backend' },
      { _id: 'sk_6', name: 'MongoDB', category: 'Database' },
      { _id: 'sk_14', name: 'REST APIs', category: 'Backend' },
      { _id: 'sk_15', name: 'Docker', category: 'DevOps & Tools' },
    ],
    qualification: {
      degree: 'B.Tech / BCA / B.Sc',
      field: 'Computer Science',
      minCgpa: 6.5,
    },
    experienceRequired: {
      minYears: 0,
      level: '0 - 1 years (Freshers eligible)',
    },
    location: {
      type: 'Hybrid',
      city: 'Bengaluru',
      state: 'Karnataka',
      country: 'India',
    },
    interests: ['Full-stack Web Development', 'Backend Engineering'],
    salary: {
      amount: '₹8,50,000',
      period: 'year',
      currency: '₹',
      isUnpaid: false,
    },
    deadline: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'Active',
    applicantCount: 38,
    description:
      'We are seeking an ambitious Junior Full-Stack Developer to work across our Node.js APIs and React frontends. You will touch real database schemas, API optimizations, and microservices.',
    responsibilities: [
      'Build RESTful API endpoints and secure authentication flows with Express.js',
      'Implement interactive React dashboards and user workflows',
      'Model Mongoose schemas and optimize database queries',
      'Deploy services using Docker containers',
    ],
    requirements: [
      'Experience building full-stack projects using React and Node.js',
      'Knowledge of NoSQL database operations',
      'Strong problem solving and architectural curiosity',
    ],
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    _id: 'opp_3',
    title: 'Product Design & UI/UX Apprentice',
    organization: 'PixelCraft Studio',
    organizationLogo: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?auto=format&fit=crop&q=80&w=200',
    type: 'Apprenticeship',
    matchScore: 78,
    requiredSkills: [
      { _id: 'sk_10', name: 'Figma', category: 'Design' },
      { _id: 'sk_11', name: 'UI/UX Design', category: 'Design' },
      { _id: 'sk_18', name: 'HTML & CSS', category: 'Frontend' },
    ],
    qualification: {
      degree: 'Any Graduate or Diploma',
      field: 'Design, Arts, or Engineering',
      minCgpa: 0,
    },
    experienceRequired: {
      minYears: 0,
      level: 'Fresher / Enthusiast',
    },
    location: {
      type: 'Remote',
      city: 'Mumbai',
      state: 'Maharashtra',
      country: 'India',
    },
    interests: ['UI/UX Design', 'Product Management'],
    salary: {
      amount: '₹22,000',
      period: 'month',
      currency: '₹',
      isUnpaid: false,
    },
    deadline: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'Active',
    applicantCount: 19,
    description:
      'A paid apprenticeship designed for passionate visual and interaction designers. Learn user research, design token systems, and design handoff while crafting consumer experiences.',
    responsibilities: [
      'Create high-fidelity wireframes and interactive prototypes in Figma',
      'Conduct usability feedback interviews with early adopters',
      'Maintain component library and token specifications',
    ],
    requirements: [
      'Portfolio with at least 2 mobile or web UI concept case studies',
      'Proficiency with Figma components, auto-layout, and styles',
    ],
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    _id: 'opp_4',
    title: 'AI & Data Science Trainee',
    organization: 'DeepSense Analytics',
    organizationLogo: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&q=80&w=200',
    type: 'Internship',
    matchScore: 65,
    requiredSkills: [
      { _id: 'sk_8', name: 'Python', category: 'Programming' },
      { _id: 'sk_9', name: 'Machine Learning', category: 'Data & AI' },
      { _id: 'sk_7', name: 'SQL', category: 'Database' },
      { _id: 'sk_17', name: 'Data Structures', category: 'Computer Science' },
    ],
    qualification: {
      degree: 'B.Tech / M.Tech / M.Sc',
      field: 'Data Science / AI / CS / Math',
      minCgpa: 7.5,
    },
    experienceRequired: {
      minYears: 0,
      level: 'Student / Fresher',
    },
    location: {
      type: 'On-site',
      city: 'Hyderabad',
      state: 'Telangana',
      country: 'India',
    },
    interests: ['Artificial Intelligence', 'Data Science', 'Machine Learning'],
    salary: {
      amount: '₹40,000',
      period: 'month',
      currency: '₹',
      isUnpaid: false,
    },
    deadline: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'Active',
    applicantCount: 31,
    description:
      'DeepSense is looking for high-curiosity student trainees to contribute to machine learning pipelines, structured ETL processes, and predictive analytics models.',
    responsibilities: [
      'Perform exploratory data analysis (EDA) and data cleansing in Python',
      'Build baseline classification and regression models',
      'Benchmark model performance metrics against business KPIs',
    ],
    requirements: [
      'Proficient in Python and mathematical foundations of ML',
      'Working knowledge of SQL joins and data extraction',
    ],
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    _id: 'opp_5',
    title: 'Cloud DevOps & Platform Trainee',
    organization: 'TechCorp Labs',
    organizationLogo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&q=80&w=200',
    type: 'Apprenticeship',
    matchScore: 71,
    requiredSkills: [
      { _id: 'sk_15', name: 'Docker', category: 'DevOps & Tools' },
      { _id: 'sk_16', name: 'AWS', category: 'Cloud' },
      { _id: 'sk_13', name: 'Git', category: 'DevOps & Tools' },
      { _id: 'sk_4', name: 'Node.js', category: 'Backend' },
    ],
    qualification: {
      degree: 'B.Tech / BCA',
      field: 'Computer Science or IT',
      minCgpa: 6.0,
    },
    experienceRequired: {
      minYears: 0,
      level: 'Fresher',
    },
    location: {
      type: 'Remote',
      city: 'Bengaluru',
      state: 'Karnataka',
      country: 'India',
    },
    interests: ['Cloud Computing', 'DevOps', 'Infrastructure'],
    salary: {
      amount: '₹30,000',
      period: 'month',
      currency: '₹',
      isUnpaid: false,
    },
    deadline: new Date(Date.now() + 40 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'Active',
    applicantCount: 15,
    description:
      'Learn how continuous deployment works at scale. Work with modern CI/CD pipelines, container orchestration, and multi-region AWS cloud deployments.',
    responsibilities: [
      'Assist in containerizing backend web applications with Docker',
      'Write GitHub Actions automation workflows',
      'Monitor server logs and system health telemetry',
    ],
    requirements: [
      'Familiarity with basic Linux commands and Git',
      'Basic networking knowledge (DNS, HTTP/S, SSL)',
    ],
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    _id: 'opp_6',
    title: 'React Native Mobile Intern',
    organization: 'FinTech Pulse',
    organizationLogo: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&q=80&w=200',
    type: 'Internship',
    matchScore: 89,
    requiredSkills: [
      { _id: 'sk_1', name: 'React', category: 'Frontend' },
      { _id: 'sk_2', name: 'JavaScript', category: 'Programming' },
      { _id: 'sk_3', name: 'TypeScript', category: 'Programming' },
      { _id: 'sk_14', name: 'REST APIs', category: 'Backend' },
    ],
    qualification: {
      degree: 'B.Tech / MCA',
      field: 'Computer Science or Software Engineering',
      minCgpa: 7.0,
    },
    experienceRequired: {
      minYears: 0,
      level: 'Student',
    },
    location: {
      type: 'Hybrid',
      city: 'Bengaluru',
      state: 'Karnataka',
      country: 'India',
    },
    interests: ['Mobile Development', 'Frontend Engineering', 'FinTech'],
    salary: {
      amount: '₹32,000',
      period: 'month',
      currency: '₹',
      isUnpaid: false,
    },
    deadline: new Date(Date.now() + 28 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'Active',
    applicantCount: 22,
    description:
      'Help build seamless cross-platform mobile finance applications using React Native. Work directly with banking APIs, secure biometric auth, and animated transactional charts.',
    responsibilities: [
      'Develop pixel-perfect mobile screens using React Native and TypeScript',
      'Integrate secure REST APIs and handle offline state synchronization',
      'Debug cross-device UI inconsistencies on iOS and Android',
    ],
    requirements: [
      'Solid command of JavaScript and React concepts',
      'Familiarity with mobile layout principles',
    ],
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const INITIAL_LEARNING_RESOURCES = [
  {
    _id: 'lr_1',
    title: 'Node.js & Express Fundamentals',
    description: 'Master backend server development, routing, middleware, and database connectivity.',
    skill: { _id: 'sk_4', name: 'Node.js' },
    type: 'Course',
    url: 'https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs',
    provider: 'MDN Web Docs',
    difficulty: 'Beginner',
    estimatedDuration: '4 hours',
    roadmapStage: 'Beginner',
  },
  {
    _id: 'lr_2',
    title: 'MongoDB Schema Design & Query Optimization',
    description: 'Learn document modeling, indexing strategies, and aggregation pipelines.',
    skill: { _id: 'sk_6', name: 'MongoDB' },
    type: 'Documentation',
    url: 'https://www.mongodb.com/developer/products/mongodb/schema-design-best-practices/',
    provider: 'MongoDB University',
    difficulty: 'Intermediate',
    estimatedDuration: '3 hours',
    roadmapStage: 'Practice',
  },
  {
    _id: 'lr_3',
    title: 'TypeScript for JavaScript Developers',
    description: 'Understand static typing, generics, interfaces, and strict type safety.',
    skill: { _id: 'sk_3', name: 'TypeScript' },
    type: 'Course',
    url: 'https://www.typescriptlang.org/docs/handbook/typescript-in-5-minutes.html',
    provider: 'TypeScript Official',
    difficulty: 'Beginner',
    estimatedDuration: '2 hours',
    roadmapStage: 'Beginner',
  },
  {
    _id: 'lr_4',
    title: 'Complete Docker Hands-On for Beginners',
    description: 'Build container images, run microservices with docker-compose, and manage ports.',
    skill: { _id: 'sk_15', name: 'Docker' },
    type: 'Video',
    url: 'https://docs.docker.com/get-started/',
    provider: 'Docker Labs',
    difficulty: 'Intermediate',
    estimatedDuration: '3.5 hours',
    roadmapStage: 'Practice',
  },
  {
    _id: 'lr_5',
    title: 'Modern UI/UX Design with Figma',
    description: 'Wireframing, typography hierarchies, auto-layout, design tokens and prototyping.',
    skill: { _id: 'sk_10', name: 'Figma' },
    type: 'Course',
    url: 'https://help.figma.com/hc/en-us/categories/360002051613-Figma-design',
    provider: 'Figma Community Academy',
    difficulty: 'Beginner',
    estimatedDuration: '5 hours',
    roadmapStage: 'Project',
  },
  {
    _id: 'lr_6',
    title: 'Practical Machine Learning with Scikit-Learn',
    description: 'Data preprocessing, feature engineering, classification, and evaluation metrics.',
    skill: { _id: 'sk_9', name: 'Machine Learning' },
    type: 'Article',
    url: 'https://scikit-learn.org/stable/tutorial/basic/tutorial.html',
    provider: 'Scikit-Learn Docs',
    difficulty: 'Advanced',
    estimatedDuration: '6 hours',
    roadmapStage: 'Ready',
  },
  {
    _id: 'lr_7',
    title: 'Building Production REST APIs with Authentication',
    description: 'JWT token lifecycle, password hashing with bcrypt, input validation, and HTTP security.',
    skill: { _id: 'sk_14', name: 'REST APIs' },
    type: 'Course',
    url: 'https://expressjs.com/en/guide/routing.html',
    provider: 'OpenPath Engineering',
    difficulty: 'Intermediate',
    estimatedDuration: '3 hours',
    roadmapStage: 'Practice',
  },
  {
    _id: 'lr_8',
    title: 'AWS Cloud Practitioner Essentials',
    description: 'Cloud concepts, security architecture, IAM roles, S3 buckets, and EC2 instances.',
    skill: { _id: 'sk_16', name: 'AWS' },
    type: 'Course',
    url: 'https://aws.amazon.com/training/digital/aws-cloud-practitioner-essentials/',
    provider: 'AWS Skill Builder',
    difficulty: 'Intermediate',
    estimatedDuration: '6 hours',
    roadmapStage: 'Ready',
  },
];

export const INITIAL_APPLICATIONS = [
  {
    _id: 'app_1',
    opportunity: INITIAL_OPPORTUNITIES[0],
    student: DEMO_STUDENT,
    status: 'Shortlisted',
    appliedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    matchScore: 94,
    timeline: [
      { status: 'Applied', timestamp: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(), note: 'Application submitted via OpenPath 1-click apply' },
      { status: 'Reviewing', timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(), note: 'Resume and profile under technical evaluation' },
      { status: 'Shortlisted', timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(), note: 'Candidate profile cleared initial criteria (94% Match)' },
    ],
    interviewDetails: {
      date: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString(),
      format: 'Google Meet',
      link: 'https://meet.google.com/xyz-openpath-demo',
      instructions: 'Technical round focusing on React components and live problem solving.',
    },
    notes: 'Very excited to contribute to the frontend design system!',
  },
  {
    _id: 'app_2',
    opportunity: INITIAL_OPPORTUNITIES[1],
    student: DEMO_STUDENT,
    status: 'Reviewing',
    appliedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    matchScore: 82,
    timeline: [
      { status: 'Applied', timestamp: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(), note: 'Application submitted via OpenPath' },
      { status: 'Reviewing', timestamp: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(), note: 'Hiring manager reviewing project portfolio' },
    ],
    notes: 'Experienced with Node.js and building fullstack applications.',
  },
];
